name: CI/CD PIPELINE

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Hugo
      run: |
        sudo apt-get install hugo

    - name: Build Website
      run: hugo--destination public

    - name: Deploy to Hosting Service
      # Add deployment steps here, e.g., deploying to GitHub Pages, Netlify, or AWS S3.
